### ISSUE TITLE
Align Typescript & Runtype names

### ISSUE THREAD

**Issue by johngeorgewright** [runtypes/runtypes#282]
I understand this request is somewhat controversial, so I'm expecting some resistance, and that is totally reasonable. I'm sure you have thought long and hard about your naming conventions, but as I foresee a major release coming up, I thought it's a good time to chuck this spanner in the works and see if there's anyone else that feels the same.

I'm slowly bringing in the runtypes package in to our development process, at my place of work, as I love it's API and the codebase is easy to work with. However, 1 thing that has initially caused some confusion in my team (especially those new to Typescript) is the naming of `Record` & `Dictionary`.

Because Typescript has already chosen to use a type `Record` in a similar way to what you've chosen to name `Dictionary`, and you've chosen to use `Record` as a kind of `Object` validator, it seems there could be something more obvious and consistent.

How would you feel about using `Object` instead of `Record` & `Record` instead of `Dictionary`?

```typescript
import { Object, Record, Number, String } from 'runtypes'

const a = Object({ foo: 'bar' })

const b = Record(String, Number) // I've also swapped the key/value parameters here to match typescript
```

This could well be considered more confusing, now that the community is used to the current naming, however, a part of me thinks it would be easier to get on board with if it was more aligned with Typescript.

Food for thought.

**Comment by yuhr** [comment]
Yeahhh this is what I've been thinking for a long time, I'm glad to see you have provided some momentum. Generally speaking changing names of APIs could be a huge surprise to users and requires intermediate deprecation notices, but this time it would apparently be a quite reasonable change.

There are some remaining tasks which should be done until v7, so we shall wait to seek for any resistive opinions in this issue. If no one comes, we'll introduce this change in v7.

**Comment by ibezkrovnyi** [comment]
Meaning | Current naming | Proposed naming | TypeScript naming | JavaScript naming | Used in discussions<br>in our team and between teams
--- | --- | --- | -- | -- | --
[**Record** with key-value type<br>pairs known at compile-time](https://en.wikipedia.org/wiki/Record_(computer_science)) | Record | Object | Record | Object | Record or Object
[**Dictionary** or<br>associative array<br>or map](https://en.wikipedia.org/wiki/Associative_array) | Dictionary | Record | Record | Object or Map | Dictionary or Object

I'm voting to keep current naming - it is accurate, comes from Data Structures theory and everyone (at least I have such experience) clearly understands the meaning - this is important additional benefit in communication with non-typescript devs: javascript and java devs, managers.
